// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCK-P0tk97Yy53O_SmErh18Vp5ZhzyKz6w',
    appId: '1:506055875645:android:112561a803efcdffcf5e54',
    messagingSenderId: '506055875645',
    projectId: 'signin-96a21',
    storageBucket: 'signin-96a21.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9XLI0XAiSL5kXn6udePgF9gjj6-o8NaM',
    appId: '1:506055875645:web:765bde606a649b8dcf5e54',
    messagingSenderId: '506055875645',
    projectId: 'signin-96a21',
    authDomain: 'signin-96a21.firebaseapp.com',
    storageBucket: 'signin-96a21.firebasestorage.app',
    measurementId: 'G-B8WNKDXPWN',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5Rv0ZSVt1BAo0ur4gtyePCizbMtSt-v0',
    appId: '1:506055875645:ios:977c7583f53eb991cf5e54',
    messagingSenderId: '506055875645',
    projectId: 'signin-96a21',
    storageBucket: 'signin-96a21.firebasestorage.app',
    androidClientId: '506055875645-4ovmehckft2lkhanqp2053cn7tjribo4.apps.googleusercontent.com',
    iosClientId: '506055875645-qti98o8smqsg5e8ehui5fjj9vsnk26tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.sapMobile',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5Rv0ZSVt1BAo0ur4gtyePCizbMtSt-v0',
    appId: '1:506055875645:ios:977c7583f53eb991cf5e54',
    messagingSenderId: '506055875645',
    projectId: 'signin-96a21',
    storageBucket: 'signin-96a21.firebasestorage.app',
    androidClientId: '506055875645-4ovmehckft2lkhanqp2053cn7tjribo4.apps.googleusercontent.com',
    iosClientId: '506055875645-qti98o8smqsg5e8ehui5fjj9vsnk26tm.apps.googleusercontent.com',
    iosBundleId: 'com.example.sapMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9XLI0XAiSL5kXn6udePgF9gjj6-o8NaM',
    appId: '1:506055875645:web:0d13fe7a17e97d6fcf5e54',
    messagingSenderId: '506055875645',
    projectId: 'signin-96a21',
    authDomain: 'signin-96a21.firebaseapp.com',
    storageBucket: 'signin-96a21.firebasestorage.app',
    measurementId: 'G-M4TF7PGZF9',
  );

}